App\Entity\User:
    properties:
        email:
            - Email:
                message: The email "{{ value }}" is not a valid email.
        username:
            - Length:
                min: 3
                max: 25
                minMessage: 'Your username must be at least {{ limit }} characters long'
                maxMessage: 'Your username cannot be longer than {{ limit }} characters'

App\Entity\UserCredentials:
    properties:
      password:
        - Length:
            min: 8
            max: 50
            minMessage: 'Your password must be at least {{ limit }} characters long'
            maxMessage: 'Your password cannot be longer than {{ limit }} characters'
